### ISSUE TITLE
TODO list for workshop notebooks

### ISSUE THREAD

**Issue by megies** [obspy/docs#7]
TODO list for https://github.com/obspy/docs/tree/master/workshops/2016-03-07_ipgp:
 - [ ] remove all mention of `.attach_response()` and replace by `.remove_response(inventory, ...)`
 - [ ] add basic instruction info for notebook `08` "basic processing exercise" (data in provided files is from `INGV` fdsnws and not the usual `IRIS` default of other notebooks, so currently the whole notebook is very confusing)
 - [ ] some parts are duplicated (e.g. basic Trace intro in first notebook and in "waveform data" notebook, could use some refactoring)
 - [ ] ...

**Comment by krischer** [comment]
> some parts are duplicated (e.g. basic Trace intro in first notebook and in "waveform data" notebook, could use some refactoring)

This is actually intentional and I have some fairly good experiences with it but I agree that it might have to be toned down a bit. The basic idea is to give users (who might have never seen ObsPy before) a quick overview over the three core classes and the three main `read()` methods and then dive into the details of each.
